name: CI Pipeline with Slack Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Notify Slack of build result
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Build succeeded on branch ${{ github.ref }} for repo ${{ github.repository }}"}' \
            $SLACK_WEBHOOK_URL
          else
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Build failed on branch ${{ github.ref }} for repo ${{ github.repository }}. Please check the logs."}' \
            $SLACK_WEBHOOK_URL
          fi
